/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica01;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import javafx.stage.Screen;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author dam2
 */
public class fraVentana extends javax.swing.JFrame {

    /**
     * Creates new form fraVentana
     */
    public fraVentana() {
       
        initComponents();
        setTitle("Centro "+this.getSize().width+" X "+this.getSize().height);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArribaDcha = new javax.swing.JButton();
        btnArribaIzda = new javax.swing.JButton();
        btnAbajoIzda = new javax.swing.JButton();
        btnAbajoDcha = new javax.swing.JButton();
        tglDimension = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(400, 200, 300, 300));
        setLocation(new java.awt.Point(400, 200));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setSize(new java.awt.Dimension(300, 300));

        btnArribaDcha.setText("Arriba Derecha");
        btnArribaDcha.setName("btnArribaDcha"); // NOI18N
        btnArribaDcha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArribaDchaMouseClicked(evt);
            }
        });

        btnArribaIzda.setText("Arriba Izquierda");
        btnArribaIzda.setName("btnArribaIzda"); // NOI18N
        btnArribaIzda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArribaIzdaMouseClicked(evt);
            }
        });

        btnAbajoIzda.setText("Abajo Izquierda");
        btnAbajoIzda.setName("btnAbajoIzda"); // NOI18N
        btnAbajoIzda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbajoIzdaMouseClicked(evt);
            }
        });

        btnAbajoDcha.setText("Abajo Derecha");
        btnAbajoDcha.setName("Abajo Derecha"); // NOI18N
        btnAbajoDcha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbajoDchaMouseClicked(evt);
            }
        });

        tglDimension.setText("Aumentar dimension");
        tglDimension.setAlignmentY(0.0F);
        tglDimension.setName("tglDimension"); // NOI18N
        tglDimension.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tglDimensionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnArribaIzda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnArribaDcha))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAbajoIzda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnAbajoDcha))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(tglDimension)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArribaDcha)
                    .addComponent(btnArribaIzda))
                .addGap(112, 112, 112)
                .addComponent(tglDimension)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbajoIzda)
                    .addComponent(btnAbajoDcha)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setTitle(String title) {
        super.setTitle(title); //To change body of generated methods, choose Tools | Templates.
    }
   
    
    public fraVentana(JButton btnAbajoDcha, JButton btnAbajoIzda, JButton btnArribaDcha, JButton btnArribaIzda) throws HeadlessException {
        this.btnAbajoDcha = btnAbajoDcha;
        this.btnAbajoIzda = btnAbajoIzda;
        this.btnArribaDcha = btnArribaDcha;
        this.btnArribaIzda = btnArribaIzda;
    }
    
// Evento ligado a clic sobre boton arriba derecha
    private void btnArribaDchaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArribaDchaMouseClicked
        
      this.setLocation(550, 50);
      this.setTitle(btnArribaDcha.getText()+" " + this.getSize().width +" X "+this.getSize().height);
      
    }//GEN-LAST:event_btnArribaDchaMouseClicked

// Evento ligado a clic sobre boton arriba izquierda
    private void btnArribaIzdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArribaIzdaMouseClicked
        
        this.setLocation(250, 50);
        this.setTitle(btnArribaIzda.getText()+" " + this.getSize().width +" X "+this.getSize().height);
    }//GEN-LAST:event_btnArribaIzdaMouseClicked

// Evento ligado a clic sobre boton abajo izquierda
    private void btnAbajoIzdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbajoIzdaMouseClicked
        
        this.setLocation(250, 350);
        this.setTitle(btnAbajoIzda.getText()+" " + this.getSize().width +" X "+this.getSize().height);
    }//GEN-LAST:event_btnAbajoIzdaMouseClicked

// Evento ligado a clic sobre boton abajo derecha    
    private void btnAbajoDchaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbajoDchaMouseClicked
         
        this.setLocation(550, 350);
        this.setTitle(btnAbajoDcha.getText()+" " + this.getSize().width +" X "+this.getSize().height);
    }//GEN-LAST:event_btnAbajoDchaMouseClicked

// Evento ligado a clic sobre botón que cambia dimension del jFrame
    private void tglDimensionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglDimensionMouseClicked
        
        
        if(tglDimension.isSelected()){
            this.setSize(600, 600);
            tglDimension.setText("Disminuye dimensión");
            this.getContentPane().setBackground(Color.cyan);
            
        }
        
        if(!tglDimension.isSelected()){
            this.setSize(300, 300);
            tglDimension.setText("Aumenta dimensión");
            this.getContentPane().setBackground(Color.GREEN);
            
        }
        
       // Actualizar posición del jFrame
        this.setTitle(this.getSize().width +" x "+this.getSize().height);
        
    }//GEN-LAST:event_tglDimensionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fraVentana().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbajoDcha;
    private javax.swing.JButton btnAbajoIzda;
    private javax.swing.JButton btnArribaDcha;
    private javax.swing.JButton btnArribaIzda;
    private javax.swing.JToggleButton tglDimension;
    // End of variables declaration//GEN-END:variables
}
